spring.application.name=HomeServices
spring.datasource.url=jdbc:mysql://25.21.56.83:3306/home_services
spring.datasource.username=polina
spring.datasource.password=ilyushin1718A

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true